---
- name: download Wordpress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: /tmp/wordpress.tar.gz
    sha256sum: "{{ wordpress_sha256_sum }}"

- name: install python-mysqldb
  sudo: yes
  apt:
    pkg: python-mysqldb
    state: latest

- name: ensure /var/www/wordpress exists
  sudo: yes
  file:
    path: /var/www/wordpress
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
    state: directory

- name: unpack Wordpress
  sudo: yes
  sudo_user: "{{ webapp_user }}"
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/wordpress
    copy: no

- name: add DB for wordpress
  sudo: yes
  mysql_db:
    name: wordpress
    state: present

- name: add DB user for wordpress
  sudo: yes
  mysql_user:
    name: wordpress
    password: "{{ wordpress_password }}"
    priv: wordpress.*:ALL
    state: present

- name: configure php-fpm
  sudo: yes
  template:
    src: php/wordpress.conf.j2
    dest: /etc/php5/fpm/pool.d/wordpress.conf
    owner: root
    group: root
  notify:
    - reload php-fpm

- name: configure nginx
  sudo: yes
  template:
    src: nginx/wordpress.conf
    dest: /etc/nginx/sites-available/wordpress.conf
    owner: root
    group: root
  notify:
    - reload nginx

- name: enable wordpress config in nginx
  sudo: yes
  file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    owner: root
    group: root
    state: link
  notify:
    - reload nginx

- name: configure wordpress variables
  sudo: yes
  template:
    src: wordpress/wp-config.php.j2
    dest: /var/www/wordpress/wordpress/wp-config.php
    owner: "{{ webapp_user }}"
    group: "{{ webapp_user }}"
