---
- name: create html directory
  sudo: yes
  file:
    path: /var/lib/docker/volumes/wordpress/html
    owner: root
    group: root
    state: directory

- name: add wordpress service
  sudo: yes
  template:
    src: wordpress.service.j2
    dest: /lib/systemd/system/wordpress.service
    owner: root
    group: root
  notify:
    - restart wordpress
    - restart nginx

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start wordpress service
  sudo: yes
  service:
    name: wordpress
    enabled: yes
    state: started
