---
- name: create nginx conf.d
  sudo: yes
  file:
    path: /var/lib/docker/volumes/nginx/conf.d
    owner: root
    group: root
    state: directory

- name: configure nginx
  sudo: yes
  template:
    src: nginx.conf.j2
    dest: /var/lib/docker/volumes/nginx/nginx.conf
    owner: root
    group: root
  notify:
    - restart nginx

- name: configure for wordpress
  sudo: yes
  template:
    src: wordpress.conf.j2
    dest: /var/lib/docker/volumes/nginx/conf.d/wordpress.conf
    owner: root
    group: root
  notify:
    - restart nginx

- name: add nginx service
  sudo: yes
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
    owner: root
    group: root
  notify:
    - restart nginx

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start nginx service
  sudo: yes
  service:
    name: nginx
    enabled: yes
    state: started
