language: python
python:
  - 2.7

install:
  - pip install ansible

script:
  - ansible-playbook -i provision/travis provision/site.yml --syntax-check

notifications:
  irc:
    channels:
      - "chat.freenode.net#one-love"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - meka@lugons.org
    on_success: change
    on_failure: always
