---
- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: install docker
  sudo: yes
  apt:
    name: docker.io
    state: latest

- name: start docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
