---
- name: create data volume
  sudo: yes
  file:
    path: /var/lib/docker/volumes/mariadb
    owner: root
    group: root
    state: directory

- name: add mariadb service
  sudo: yes
  template:
    src: mariadb.service.j2
    dest: /lib/systemd/system/mariadb.service
    owner: root
    group: root
  notify:
    - restart mariadb
    - restart wordpress
    - restart nginx

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start mariadb service
  sudo: yes
  service:
    name: mariadb
    enabled: yes
    state: started
